'use client'

import React from 'react'
import { Player } from '@remotion/player'
import { RemotionRoot } from '@/remotion/Root'
import { MyVideo } from '@/remotion/MyVideo'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function RenderPreviewPage() {
  const [titleText, setTitleText] = React.useState('Clavio Prompt-Based AI Rendering')

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-slate-900">Render Preview</h1>
        <p className="mt-0.5 text-sm text-slate-500">
          Preview and test Remotion video compositions dynamically.
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {/* Player Container */}
        <Card className="overflow-hidden">
          <CardHeader>
            <CardTitle className="text-base font-medium">Live Preview</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center p-0 bg-slate-100">
            <div className="w-full max-w-[300px] border shadow-sm">
              <Player
                component={MyVideo}
                inputProps={{
                  titleText,
                  titleColor: '#0f172a',
                }}
                durationInFrames={150}
                fps={30}
                compositionWidth={1080}
                compositionHeight={1920}
                style={{
                  width: '100%',
                }}
                controls
                autoPlay
                loop
              />
            </div>
          </CardContent>
        </Card>

        {/* Dynamic Controls */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base font-medium">Prompt Simulation</CardTitle>
            <CardDescription>
              In production, these values will be generated by Ollama based on the user prompt.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="title">Generated Title Script</Label>
              <Input
                id="title"
                value={titleText}
                onChange={(e) => setTitleText(e.target.value)}
              />
            </div>
            
            <div className="p-4 bg-slate-50 rounded-lg text-sm text-slate-600 border border-slate-100">
              <p className="font-semibold mb-1">How this works:</p>
              <ol className="list-decimal pl-4 space-y-1">
                <li>User writes prompt: "Make a video about AI"</li>
                <li>Ollama generates: <code className="bg-slate-200 px-1 rounded">titleText</code></li>
                <li>Remotion Player renders it live</li>
                <li>n8n orchestrates the final background render job</li>
              </ol>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
